spring.datasource.url=jdbc:postgresql://localhost:5432/devplatform
spring.datasource.username=devplatform
spring.datasource.password=devplatform

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true