apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev-platform
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devplatform
  SPRING_RABBITMQ_HOST: rabbitmq
  DEVPLATFORM_RABBIT_EXCHANGE: deployments
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev-platform
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: changeme
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: dev-platform
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: devplatform
