apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dev-platform
data:
  DEVPLATFORM_RABBIT_EXCHANGE: deployments
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.dev-platform.svc.cluster.local:5432/devplatform
  SPRING_RABBITMQ_HOST: rabbitmq.dev-platform.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: dev-platform
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: dev-platform
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: devplatform
