apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dev-platform.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/{{ .Values.postgres.database }}
  SPRING_RABBITMQ_HOST: rabbitmq
  DEVPLATFORM_RABBIT_EXCHANGE: deployments
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dev-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password }}
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dev-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  POSTGRES_DB: {{ .Values.postgres.database }}
