backend:
  image:
    repository: ghcr.io/addison-fogle/dev-platform-backend
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi
  probes:
    readiness:
      initialDelaySeconds: 20
      periodSeconds: 10
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 15

frontend:
  image:
    repository: ghcr.io/addison-fogle/dev-platform-frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

postgres:
  image: postgres:17
  storage: 5Gi
  storageClass: gp2
  username: postgres
  password: postgres
  database: devplatform
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

rabbitmq:
  image: rabbitmq:4-management
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

ingress:
  host: dev-platform.local
  className: nginx

serviceMonitor:
  enabled: true
  interval: 30s
